CXX = g++
CXXFLAGS = -Wall

lab7: Song.o lab9.cpp
	$(CXX) $(CXXFLAGS) Song.o lab9.cpp -o lab9

StudentRecord.o: Song.cpp Song.h
	$(CXX) $(CXXFlAGS) -c Song.cpp

clean:
	rm *.o*
	rm *~

run:
	./lab9



